IT-957: Add VPC gateway endpoints
Sage-Bionetworks/scipool-infra pull request #188
Opened 2020-09-10 19:31 UTC by xschildw

[IT-957]
This PR adds VPC gateway endpoints in cesspoolvpc and internalpoolvpc. This should ensure that we don't incur NAT charges when pushing data from EC2 instances in these VPCs to S3.

2020-09-15 21:45 UTC, zaro0508 approved these changes
would be nice to set this up on every one of our AWS accounts

2020-09-17 15:32 UTC, brucehoff requested changes

2020-09-17 15:32 UTC, brucehoff commented on config/develop/s3-cesspoolvpc-gateway-endpoint.yaml
> +  - prod/cesspoolvpc.yaml
should this be "develop/cesspoolvpc.yaml"?

2020-09-17 18:49 UTC, brucehoff approved these changes

2020-09-21 18:34 UTC, merged