SC-254 define dynamodb table to hold marketplace registration info
Sage-Bionetworks/scipool-infra pull request #214
Opened 2020-10-21 00:09 UTC by brucehoff

define dynamodb table to hold marketplace registration info

2020-10-21 19:00 UTC, ahayden approved these changes

2020-10-21 19:38 UTC, zaro0508 requested changes

2020-10-22 22:27 UTC, brucehoff commented on config/develop/cfn-marketplace-dynamo.yaml
> +  - "develop/essentials.yaml"
ok

2020-10-22 22:28 UTC, brucehoff commented on templates/cfn-marketplace-dynamo.yaml
> +          AttributeType: S
Although it appears like a number (generated from a SQL sequence), it's represented and passed around (e.g. in JSON objects) as a string.

2020-10-22 23:51 UTC, brucehoff commented on templates/cfn-marketplace-dynamo.yaml
> +      TableName: MarketplaceRegistration
OK.  Will have to work through how to pass the generated table name to the code that uses it.

2020-10-22 23:59 UTC, brucehoff commented on templates/cfn-marketplace-dynamo.yaml
> +
No, only the attribute(s) used in the key are defined.  See https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/getting-started-step-1.html
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/getting-started-step-2.html

2020-10-23 00:02 UTC, brucehoff commented on templates/cfn-marketplace-dynamo.yaml
> +        - !Ref SynapseLoginInstanceRoleArn
SynapseLoginInstanceRole is simply the role used to run the login app'.  It's independent of any Synapse user.  The Synapse user becomes involved only when the ServiceCatalogEndusers role is assumed and that does not happen until after the user logs into Synapse.

2020-10-23 00:05 UTC, brucehoff commented on templates/cfn-marketplace-dynamo.yaml
> +Description: Set up DynamoDB for AWS Marketplace registration
ok

2020-10-23 00:18 UTC, brucehoff commented on templates/cfn-marketplace-dynamo.yaml
> +  DynamoDBTable:
I added as an output the table name, since that's what's used to issue dynamodb requests.  Not sure if anything else needs to be exported.

2020-10-23 00:21 UTC, brucehoff commented on templates/login-role-marketplace-policy.yaml
> +Description: "Policy that lets the Synapse login role resolve marketplace customer"
I'm not sure why.  It's easy to do, but that service will not be called by the synapse login role, will it?

2020-10-23 00:21 UTC, brucehoff commented on templates/login-role-marketplace-policy.yaml
> +Description: "Policy that lets the Synapse login role resolve marketplace customer"
sure!

2020-10-23 16:52 UTC, tthyer approved these changes

2020-10-23 22:38 UTC, zaro0508 commented on templates/cfn-marketplace-dynamo.yaml
> +
Maybe I'm not getting it but all those examples seem to clearly indicate that there are multiple attributes and it looks like you need to create them in the dynamo table.

2020-10-23 22:44 UTC, zaro0508 requested changes

2020-10-23 22:44 UTC, zaro0508 commented on config/develop/idp-marketplace-policy.yaml
> +  - "develop/essentials.yaml"
this also depends on   `develop/synapse-oidc-idp.yaml`

2020-10-23 23:27 UTC, brucehoff commented on templates/cfn-marketplace-dynamo.yaml
> +
> Maybe I'm not getting it but all those examples seem to clearly indicate that there are multiple attributes and it looks like you need to create them in the dynamo table.

No, that's not how DynamoDB works.  You only define attributes for the fields that you query on.

Here's a blog that gives the example of defining an attribute Username and then adding data records with Username, Name, Age: https://www.dynamodbguide.com/inserting-retrieving-items/

We have this working test, https://github.com/Sage-Bionetworks/synapse-login-scipool/pull/59/files#diff-16fefde5032c368a31943291aae39ff843a7d0b13186c50ca26ae20e2481f772. Note that the table definition exactly mirrors the CFN in this repo' (but it's written using the DynamoDB Java client) and then it inserts fields that are not defined in the table schema.

2020-10-25 05:21 UTC, zaro0508 commented on templates/cfn-marketplace-dynamo.yaml
> +
ok, sounds good

2020-10-26 15:30 UTC, zaro0508 approved these changes

2020-10-27 00:12 UTC, merged