SC-254 remove dependency on SynapseLoginInstanceRole
Sage-Bionetworks/scipool-infra pull request #222
Opened 2020-11-05 02:29 UTC by brucehoff

instead of referencing SynapseLoginInstanceRole we *export* the managed policies and let synapse-login-aws-infra apply the managed policies to the role.  This maintains the correct order of dependencies (breaks the existing circular dependency).

2020-11-05 17:04 UTC, zaro0508 requested changes

2020-11-05 22:05 UTC, zaro0508 requested changes

2020-11-05 22:05 UTC, zaro0508 commented on templates/marketplace-dynamo.yaml
> +  DynamoRWPolicyArn:
come to think about it.  we should allow access where it's needed therefore i think we should move `DynamoRWPolicy` to synapse-login-aws-infra as well.  just replace `!GetAtt DynamoDBTable.Arn` with an ImportValue reference.

2020-11-05 22:59 UTC, brucehoff commented on templates/marketplace-dynamo.yaml
> +  DynamoRWPolicyArn:
In its current form the PR creates the managed policy close to the creation of the resource it references.  (It doesn't "allow access".  That only happens when the managed policy is applied to a role, which is done over in synapse-scipool-aws-infra.) I think the question is whether access to the DynamoDB is limited to the login app'.  If it were then I would agree that it makes sense to define the managed policy there.  But since other service catalog components can access the DB I think it makes more sense to leave it here.  Do you agree?

2020-11-06 00:10 UTC, zaro0508 commented on templates/marketplace-dynamo.yaml
> +  DynamoRWPolicyArn:
no, because policies are cheap and there's not limit in AWS so we should just make them as needed, where ever they are needed.  Also other things may want access to the DB but not necessarily with the same access level as defined in this policy.

2020-11-06 15:28 UTC, zaro0508 approved these changes
Looks good.  would you mind updating the PR message?  also this PR should depend on https://github.com/Sage-Bionetworks/synapse-login-aws-infra/pull/54

2020-11-06 15:56 UTC, brucehoff commented
> Looks good. would you mind updating the PR message? also this PR should depend on [Sage-Bionetworks/synapse-login-aws-infra#54](https://github.com/Sage-Bionetworks/synapse-login-aws-infra/pull/54)

Done

2020-11-06 15:56 UTC, merged