Add standard SSL policy
Sage-Bionetworks/scipool-infra pull request #235
Opened 2020-12-03 03:09 UTC by ahayden

This adds an SSL policy beyond the default to the notebook ALB and will not require replacement. 

It passes pre-commit, but I'm not able to validate the template or push it to a test env.

2020-12-03 07:22 UTC, zaro0508 requested changes

2020-12-03 07:22 UTC, zaro0508 commented on templates/alb-notebook-access.yaml
> +      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
why not the latest one, `ELBSecurityPolicy-TLS-1-2-Ext-2018-06`?

https://aws.amazon.com/about-aws/whats-new/2018/06/application-load-balancer-adds-new-security-policies-including-policy-for-forward-secrecy/

2020-12-07 22:53 UTC, ahayden commented on templates/alb-notebook-access.yaml
> +      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
Looks good to... I don't know of a downside. Updated

2020-12-08 22:09 UTC, zaro0508 approved these changes

2020-12-09 00:04 UTC, merged